# Generated by Django 4.2.7 on 2025-12-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='receiver_duties',
            field=models.TextField(blank=True),
        ),
    ]
