# Generated by Django 4.2.7 on 2025-11-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(choices=[('singaporean', 'Singaporean'), ('malaysian', 'Malaysian'), ('indonesian', 'Indonesian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('filipino', 'Filipino'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('british', 'British'), ('american', 'American'), ('australian', 'Australian'), ('canadian', 'Canadian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('german', 'German'), ('french', 'French'), ('other', 'Other')], default='singaporean', max_length=50, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('local', 'Local Singaporean'), ('tourist', 'Tourist'), ('vendor', 'Food Vendor'), ('tour_operator', 'Tour Operator')], default='tourist', max_length=20, verbose_name='User Type'),
        ),
    ]
