# Generated by Django 4.2.7 on 2025-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('local', 'Local Singaporean Resident'), ('tourist', 'Tourist'), ('vendor', 'F&B Vendor'), ('tour_operator', 'Tour Operator')], default='tourist', max_length=20, verbose_name='User Type'),
        ),
    ]
