# Generated by Django 4.2.7 on 2025-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_itinerarynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarynote',
            options={'ordering': ['date', 'order', '-created_at']},
        ),
        migrations.AddField(
            model_name='itinerarynote',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
