# Generated by Django 4.2.7 on 2025-11-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AlterModelOptions(
            name='touritinerary',
            options={'ordering': ['stop_order'], 'verbose_name': 'Tour Itinerary', 'verbose_name_plural': 'Tour Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='touroperator',
            options={'verbose_name': 'Tour Operator', 'verbose_name_plural': 'Tour Operators'},
        ),
        migrations.RemoveField(
            model_name='touroperator',
            name='license_number',
        ),
        migrations.AddField(
            model_name='touroperator',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='has_insurance',
            field=models.BooleanField(default=False, help_text='Has valid public liability insurance', verbose_name='Public Liability Insurance'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='natas_member',
            field=models.BooleanField(default=False, help_text='Member of National Association of Travel Agents Singapore', verbose_name='NATAS Member'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='natas_membership_number',
            field=models.CharField(blank=True, help_text='If applicable', max_length=50, verbose_name='NATAS Membership Number'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='singapore_license_number',
            field=models.CharField(blank=True, help_text='e.g., 12345 (STB license number)', max_length=50, verbose_name='Singapore Tourism Board License Number'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
