# Generated by Django 4.2.7 on 2025-11-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_event_event_cuisine_event_event_type'),
        ('tours', '0003_alter_tour_options_alter_touritinerary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritinerary',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
