# Generated by Django 4.2.7 on 2025-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_touritinerary_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritinerary',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Time spent at this stop (optional)', null=True),
        ),
    ]
