# Generated by Django 4.2.7 on 2025-11-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_touritinerary_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='booking_tourists_medium',
            field=models.BooleanField(default=False, help_text='Accept bookings for medium tourist groups (11-30 people)', verbose_name='Booking for Tourists (11 to 30)'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='booking_tourists_small',
            field=models.BooleanField(default=False, help_text='Accept bookings for small tourist groups (1-10 people)', verbose_name='Booking for Tourists (up to 10)'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='catering_tourists',
            field=models.BooleanField(default=False, help_text='Provide catering services for tourist groups', verbose_name='Catering for Tourists'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='chef_lessons',
            field=models.BooleanField(default=False, help_text='Offer cooking classes and chef demonstrations', verbose_name="Chef's Lessons"),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='kitchen_tour',
            field=models.BooleanField(default=False, help_text='Offer behind-the-scenes kitchen tours', verbose_name='Kitchen Tour'),
        ),
    ]
