# Generated by Django 4.2.7 on 2025-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_touroperator_booking_tourists_medium_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_pic',
            field=models.ImageField(blank=True, help_text='Main picture for the tour', null=True, upload_to='tour_pics/', verbose_name='Tour Picture'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='operator_pic',
            field=models.ImageField(blank=True, help_text='Profile picture for the tour operator/company', null=True, upload_to='tour_operator_pics/', verbose_name='Operator Profile Picture'),
        ),
        migrations.AlterUniqueTogether(
            name='touritinerary',
            unique_together={('tour', 'stop_order')},
        ),
    ]
