# Generated by Django 4.2.7 on 2025-11-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cuisine Type',
                'verbose_name_plural': 'Cuisine Types',
                'db_table': 'cuisine_types',
            },
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='cuisine_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='book_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_pix',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_business_pix/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kosher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_reservation',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of people per reservation (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.DecimalField(decimal_places=2, help_text='Price in SGD', max_digits=8)),
                ('dish_description', models.TextField(blank=True)),
                ('dish_pix', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_halal', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['dish_name'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='cuisine_types',
            field=models.ManyToManyField(related_name='vendors', to='vendors.cuisinetype'),
        ),
    ]
