# Generated by Django 4.2.7 on 2025-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_cuisinetype_remove_vendor_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Format: Monday: 9AM-6PM, Tuesday: 9AM-6PM, etc.'),
        ),
    ]
