# Generated by Django 4.2.7 on 2025-11-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_market_price',
            field=models.BooleanField(default=False, help_text='Check if this item has market/seasonal pricing'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dish_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in SGD', max_digits=8, null=True),
        ),
    ]
