# Generated by Django 4.2.7 on 2025-11-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_menuitem_is_market_price_alter_menuitem_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Fixed business address (for restaurants & food stalls only)', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='book_reservation',
            field=models.BooleanField(default=False, help_text='For restaurants & food stalls with fixed locations'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Fixed location latitude (for restaurants & food stalls only)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Fixed location longitude (for restaurants & food stalls only)', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='max_reservation',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of people per reservation (for restaurants & food stalls only)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Regular opening hours (for restaurants & food stalls only)'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of this specific event', max_length=200)),
                ('event_description', models.TextField(blank=True)),
                ('event_start_date', models.DateTimeField(help_text='Start date and time for this event')),
                ('event_end_date', models.DateTimeField(help_text='End date and time for this event')),
                ('event_address', models.TextField(help_text='Venue address for this specific event')),
                ('event_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('event_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Check if this specific event occurs regularly')),
                ('recurrence_pattern', models.CharField(blank=True, help_text="e.g., 'weekly', 'monthly_first_saturday'", max_length=100)),
                ('event_pix', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'vendor_type': 'event'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_events',
                'ordering': ['event_start_date'],
                'indexes': [models.Index(fields=['event_start_date', 'event_end_date'], name='vendor_even_event_s_c6f6c2_idx'), models.Index(fields=['vendor', 'event_start_date'], name='vendor_even_vendor__d6423e_idx')],
            },
        ),
    ]
