# Generated by Django 4.2.7 on 2025-11-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_address_alter_vendor_book_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='book_reservation',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='max_reservation',
        ),
        migrations.AddField(
            model_name='vendor',
            name='advance_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Required advance notice for bookings in hours'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='booking_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in Only - No Reservations'), ('call_reservation', 'Call to Reserve - Phone Booking'), ('online_reservation', 'Online Reservation - Vendor System'), ('external_reservation', 'Online Reservation - External System'), ('event_ticketing', 'Event Ticketing - External System')], default='walk_in', help_text='How customers can book this vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='external_booking_link',
            field=models.URLField(blank=True, help_text='URL for reservations or ticketing system', max_length=500, verbose_name='Booking System URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_group_size',
            field=models.PositiveIntegerField(default=0, help_text='Maximum group size allowed (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reservation_instructions',
            field=models.TextField(blank=True, help_text='Specific instructions for making reservations'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact number for reservations and inquiries', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, help_text='Business website URL'),
        ),
    ]
