# Generated by Django 4.2.7 on 2025-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_vendor_book_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_halal',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='halal',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='booking_type',
            field=models.CharField(choices=[('walk_in', 'Walk-in Only - No Reservations'), ('call_reservation', 'Call to Reserve - Phone Booking'), ('online_reservation', 'Online Reservation System'), ('event_ticketing', 'Event Ticketing - External System')], default='walk_in', help_text='How customers can book this vendor', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='external_booking_link',
            field=models.TextField(blank=True, help_text='URL(s) for reservations or ticketing system. Multiple URLs can be separated by commas or new lines.', verbose_name='Booking System URL(s)'),
        ),
    ]
