# Generated by Django 4.2.7 on 2025-11-24 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_menuitem_is_halal_remove_vendor_halal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_start_date', 'event_start_time']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, help_text='End time for this event (optional)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, help_text='Start time for this event (optional)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_website',
            field=models.URLField(blank=True, help_text='Event website or registration page URL'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(help_text='End date for this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(help_text='Start date for this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vendors.vendor'),
        ),
    ]
