# Generated by Django 4.2.7 on 2025-11-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_event_options_event_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cuisine',
            field=models.ManyToManyField(blank=True, help_text='Cuisine types featured in this event', related_name='events', to='vendors.cuisinetype'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('seasonal_promotion', 'Seasonal Promotion'), ('food_fair', 'Food Fair'), ('popup_shop', 'Pop-up Food Shop'), ('workshop', 'Cooking Workshop'), ('tasting', 'Tasting Event'), ('collaboration', 'Chef Collaboration'), ('festival', 'Food Festival'), ('other', 'Other')], default='other', help_text='Type of culinary event', max_length=50),
        ),
    ]
