# Generated by Django 4.2.7 on 2025-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_event_event_cuisine_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='accept_tour_partnership',
            field=models.BooleanField(default=False, help_text='Check if this vendor is open to partnering with food tours', verbose_name='Accepts Tour Partnerships'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='catering_service',
            field=models.BooleanField(default=False, help_text='Check if this vendor offers catering services', verbose_name='Catering Service Available'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cuisine_types',
            field=models.ManyToManyField(blank=True, help_text="Cuisine types served (leave blank for event organizers who don't cook)", related_name='vendors', to='vendors.cuisinetype'),
        ),
    ]
