# Generated by Django 4.2.7 on 2025-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendor_accept_tour_partnership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('seasonal_promotion', 'Seasonal Promotion'), ('food_fair', 'Food Fair'), ('popup_shop', 'Pop-up Food Shop'), ('workshop', 'Cooking Workshop'), ('festival', 'Food Festival'), ('other', 'Other')], default='other', help_text='Type of culinary event', max_length=50),
        ),
    ]
