# Generated by Django 4.2.7 on 2025-11-26 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_written',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
