# Generated by Django 4.2.7 on 2025-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_article_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', through='webapp.ArticleKeyword', to='webapp.keyword'),
        ),
    ]
