# Generated by Django 4.2.7 on 2025-11-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_article_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_written'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_written',
            field=models.DateField(),
        ),
    ]
