# Generated by Django 4.2.7 on 2025-11-26 11:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0009_event_event_cuisine_event_event_type'),
        ('webapp', '0004_alter_article_options_remove_article_date_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 0 to 5 stars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VendorReview',
            fields=[
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp.vendorrating')),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('is_verified_visit', models.BooleanField(default=False)),
            ],
        ),
    ]
