# Generated by Django 4.2.7 on 2025-11-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_vendorrating_vendorreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrating',
            name='review_text',
        ),
        migrations.DeleteModel(
            name='VendorReview',
        ),
    ]
